const cards = [
  [
    {
      word: 'dance',
      translation: 'танцевать',
      image: 'img/dance.jpg',
      audioSrc: 'audio/dance.mp3',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: 'img/dive.jpg',
      audioSrc: 'audio/dive.mp3',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: 'img/draw.jpg',
      audioSrc: 'audio/draw.mp3',
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: 'img/fish.jpg',
      audioSrc: 'audio/fish.mp3',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: 'img/fly.jpg',
      audioSrc: 'audio/fly.mp3',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: 'img/hug.jpg',
      audioSrc: 'audio/hug.mp3',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: 'img/jump.jpg',
      audioSrc: 'audio/jump.mp3',
    },
    {
      word: 'open',
      translation: 'открывать',
      image: 'img/open.jpg',
      audioSrc: 'audio/open.mp3',
    },
  ],
  [
    {
      word: 'play',
      translation: 'играть',
      image: 'img/play.jpg',
      audioSrc: 'audio/play.mp3',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: 'img/point.jpg',
      audioSrc: 'audio/point.mp3',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: 'img/ride.jpg',
      audioSrc: 'audio/ride.mp3',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: 'img/run.jpg',
      audioSrc: 'audio/run.mp3',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: 'img/sing.jpg',
      audioSrc: 'audio/sing.mp3',
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: 'img/skip.jpg',
      audioSrc: 'audio/skip.mp3',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: 'img/swim.jpg',
      audioSrc: 'audio/swim.mp3',
    },
    {
      word: 'drive',
      translation: 'водить машину',
      image: 'img/drive.jpg',
      audioSrc: 'audio/drive.mp3',
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      image: 'img/bird.jpg',
      audioSrc: 'audio/bird.mp3',
    },
    {
      word: 'cat',
      translation: 'кот',
      image: 'img/cat.jpg',
      audioSrc: 'audio/cat.mp3',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: 'img/chick.jpg',
      audioSrc: 'audio/chick.mp3',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: 'img/chicken.jpg',
      audioSrc: 'audio/chicken.mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: 'img/dog.jpg',
      audioSrc: 'audio/dog.mp3',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: 'img/dolphin.jpg',
      audioSrc: 'audio/dolphin.mp3',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: 'img/giraffe.jpg',
      audioSrc: 'audio/giraffe.mp3',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: 'img/horse.jpg',
      audioSrc: 'audio/horse.mp3',
    },
  ],
  [
    {
      word: 'sheep',
      translation: 'овца',
      image: 'img/sheep.jpg',
      audioSrc: 'audio/sheep.mp3',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: 'img/rabbit.jpg',
      audioSrc: 'audio/rabbit.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'img/pig.jpg',
      audioSrc: 'audio/pig.mp3',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: 'img/mouse.jpg',
      audioSrc: 'audio/mouse.mp3',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: 'img/lion.jpg',
      audioSrc: 'audio/lion.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: 'img/turtle.jpg',
      audioSrc: 'audio/turtle.mp3',
    },
    {
      word: 'parrot',
      translation: 'попугай',
      image: 'img/parrot.jpg',
      audioSrc: 'audio/parrot.mp3',
    },
    {
      word: 'cow',
      translation: 'корова',
      image: 'img/cow.jpg',
      audioSrc: 'audio/cow.mp3',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'img/skirt.jpg',
      audioSrc: 'audio/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'img/pants.jpg',
      audioSrc: 'audio/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'img/blouse.jpg',
      audioSrc: 'audio/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'img/dress.jpg',
      audioSrc: 'audio/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: 'img/boot.jpg',
      audioSrc: 'audio/boot.mp3',
    },
    {
      word: 'hat',
      translation: 'шляпа',
      image: 'img/hat.jpg',
      audioSrc: 'audio/hat.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'img/coat.jpg',
      audioSrc: 'audio/coat.mp3',
    },
    {
      word: 'scarf',
      translation: 'шарф',
      image: 'img/scarf.jpg',
      audioSrc: 'audio/scarf.mp3',
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: 'img/sad.jpg',
      audioSrc: 'audio/sad.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: 'img/angry.jpg',
      audioSrc: 'audio/angry.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'img/happy.jpg',
      audioSrc: 'audio/happy.mp3',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: 'img/tired.jpg',
      audioSrc: 'audio/tired.mp3',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: 'img/surprised.jpg',
      audioSrc: 'audio/surprised.mp3',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: 'img/scared.jpg',
      audioSrc: 'audio/scared.mp3',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: 'img/smile.jpg',
      audioSrc: 'audio/smile.mp3',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: 'img/laugh.jpg',
      audioSrc: 'audio/laugh.mp3',
    },
  ],
  [
    {
      word: 'bread',
      translation: 'хлеб',
      image: 'img/bread.jpg',
      audioSrc: 'audio/bread.mp3',
    },
    {
      word: 'cake',
      translation: 'торт',
      image: 'img/cake.jpg',
      audioSrc: 'audio/cake.mp3',
    },
    {
      word: 'chocolate',
      translation: 'шоколад',
      image: 'img/chocolate.jpg',
      audioSrc: 'audio/chocolate.mp3',
    },
    {
      word: 'eggs',
      translation: 'яйца',
      image: 'img/eggs.jpg',
      audioSrc: 'audio/eggs.mp3',
    },
    {
      word: 'ice-cream',
      translation: 'мороженое',
      image: 'img/ice_cream.jpg',
      audioSrc: 'audio/ice_cream.mp3',
    },
    {
      word: 'meat',
      translation: 'мясо',
      image: 'img/meat.jpg',
      audioSrc: 'audio/meat.mp3',
    },
    {
      word: 'sandwich',
      translation: 'сэндвич',
      image: 'img/sandwich.jpg',
      audioSrc: '/assets/audio/sandwich.mp3',
    },
    {
      word: 'soup',
      translation: 'суп',
      image: 'img/soup.jpg',
      audioSrc: 'audio/soup.mp3',
    },
  ],
  [
    {
      word: 'windy',
      translation: 'ветренно',
      image: 'img/windy.jpg',
      audioSrc: 'audio/windy.mp3',
    },
    {
      word: 'tornado',
      translation: 'торнадо',
      image: 'img/tornado.jpg',
      audioSrc: 'audio/tornado.mp3',
    },
    {
      word: 'sunny',
      translation: 'солнечно',
      image: 'img/sunny.jpg',
      audioSrc: 'audio/sunny.mp3',
    },
    {
      word: 'stormy',
      translation: 'гроза',
      image: 'img/stormy.jpg',
      audioSrc: 'audio/stormy.mp3',
    },
    {
      word: 'snowy',
      translation: 'снег',
      image: 'img/snowy.jpg',
      audioSrc: 'audio/snowy.mp3',
    },
    {
      word: 'rainy',
      translation: 'дождь',
      image: 'img/rainy.jpg',
      audioSrc: 'audio/rainy.mp3',
    },
    {
      word: 'foggy',
      translation: 'туман',
      image: 'img/foggy.jpg',
      audioSrc: 'audio/foggy.mp3',
    },
    {
      word: 'cloudy',
      translation: 'облачно',
      image: 'img/cloudy.jpg',
      audioSrc: 'audio/cloudy.mp3',
    },
  ],
]

export default cards;
